title: Awesome webpage with GitHub
author: HR-14
email: hribera@lageo.com.sv
description: > # this means to ignore newlines until "baseurl:"
  New awesome site where knowledge of geothermal energy, electric generation, database handling, and webpage creation comes together.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  HR-14

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
